import type { PresetProps } from "./types";

export function createDefaultPresets(): PresetProps[] {
  return [
    {
      id: "orbital-navigation",
      type: "OrbitalNavigationPanel",
      x: 112,
      y: 96,
      width: 520,
      height: 760,
      scale: 1,
      rotation: 0,
      opacity: 1,
      visible: true,
      zIndex: 1,
      params: {},
    },
    {
      id: "material-color",
      type: "MaterialColorPanel",
      x: 112,
      y: 654,
      width: 500,
      height: 300,
      scale: 1,
      rotation: 0,
      opacity: 1,
      visible: true,
      zIndex: 2,
      params: {
        selectedMaterial: "metallic",
        selectedColor: "purple",
      },
    },
    {
      id: "ship-detail",
      type: "ShipDetailPanel",
      x: 1250,
      y: 146,
      width: 520,
      height: 760,
      scale: 1,
      rotation: 0,
      opacity: 1,
      visible: true,
      zIndex: 3,
      params: {},
    },
    {
      id: "component-library",
      type: "ComponentLibrary",
      x: 1250,
      y: 146,
      width: 520,
      height: 960,
      scale: 1,
      rotation: 0,
      opacity: 1,
      visible: true,
      zIndex: 4,
      params: {},
    },
    {
      id: "orbital-overview",
      type: "OrbitalOverview",
      x: 112,
      y: 900,
      width: 680,
      height: 320,
      scale: 1,
      rotation: 0,
      opacity: 1,
      visible: true,
      zIndex: 5,
      params: {},
    },
  ];
}
