import type { PresetProps } from "./types";

export function createDefaultPresets(): PresetProps[] {
  return [
    {
      id: "orbital-navigation",
      type: "OrbitalNavigationPanel",
      x: 112,
      y: 96,
      width: 520,
      height: 760,
      scale: 1,
      rotation: 0,
      opacity: 1,
      visible: true,
      zIndex: 1,
      params: {},
    },
    {
      id: "material-color",
      type: "MaterialColorPanel",
      x: 112,
      y: 654,
      width: 500,
      height: 300,
      scale: 1,
      rotation: 0,
      opacity: 1,
      visible: true,
      zIndex: 2,
      params: {
        selectedMaterial: "metallic",
        selectedColor: "purple",
      },
    },
    {
      id: "ship-detail",
      type: "ShipDetailPanel",
      x: 1250,
      y: 146,
      width: 520,
      height: 760,
      scale: 1,
      rotation: 0,
      opacity: 1,
      visible: true,
      zIndex: 3,
      params: {},
    },
    {
      id: "component-library",
      type: "ComponentLibrary",
      x: 1250,
      y: 146,
      width: 520,
      height: 960,
      scale: 1,
      rotation: 0,
      opacity: 1,
      visible: true,
      zIndex: 4,
      params: {},
    },
    {
      id: "orbital-overview",
      type: "OrbitalOverview",
      x: 112,
      y: 900,
      width: 680,
      height: 320,
      scale: 1,
      rotation: 0,
      opacity: 1,
      visible: true,
      zIndex: 5,
      params: {},
    },
    {
      id: "system-diagnostics",
      type: "SystemDiagnosticsPanel",
      x: 142,
      y: 104,
      width: 760,
      height: 300,
      scale: 1,
      rotation: 0,
      opacity: 1,
      visible: true,
      zIndex: 6,
      params: {},
    },
    {
      id: "design-confidence",
      type: "DesignConfidenceCard",
      x: 96,
      y: 96,
      width: 560,
      height: 250,
      scale: 1,
      rotation: 0,
      opacity: 1,
      visible: true,
      zIndex: 7,
      params: {},
    },
    {
      id: "trajectory-simulation",
      type: "TrajectorySimulationCard",
      x: 70,
      y: 120,
      width: 920,
      height: 360,
      scale: 1,
      rotation: 0,
      opacity: 1,
      visible: true,
      zIndex: 8,
      params: {},
    },
    {
      id: "hull-stress-map",
      type: "HullStressMap",
      x: 116,
      y: 96,
      width: 420,
      height: 520,
      scale: 1,
      rotation: 0,
      opacity: 1,
      visible: true,
      zIndex: 9,
      params: {},
    },
    {
      id: "ship-identity",
      type: "ShipIdentityCard",
      x: 96,
      y: 96,
      width: 560,
      height: 250,
      scale: 1,
      rotation: 0,
      opacity: 1,
      visible: true,
      zIndex: 10,
      params: {},
    },
    {
      id: "ring-segment",
      type: "RingSegmentTag",
      x: 140,
      y: 120,
      width: 360,
      height: 126,
      scale: 1,
      rotation: 0,
      opacity: 1,
      visible: true,
      zIndex: 11,
      params: {},
    },
    {
      id: "thrust-vectoring",
      type: "ThrustVectoringPanel",
      x: 120,
      y: 90,
      width: 320,
      height: 430,
      scale: 1,
      rotation: 0,
      opacity: 1,
      visible: true,
      zIndex: 12,
      params: {},
    },
    {
      id: "structural-integrity",
      type: "StructuralIntegrityCard",
      x: 96,
      y: 108,
      width: 580,
      height: 220,
      scale: 1,
      rotation: 0,
      opacity: 1,
      visible: true,
      zIndex: 13,
      params: {},
    },
    {
      id: "course-vector",
      type: "CourseVectorPanel",
      x: 112,
      y: 120,
      width: 380,
      height: 230,
      scale: 1,
      rotation: 0,
      opacity: 1,
      visible: true,
      zIndex: 14,
      params: {},
    },
    {
      id: "orbital-navigation-card",
      type: "OrbitalNavigationCard",
      x: 96,
      y: 90,
      width: 620,
      height: 460,
      scale: 1,
      rotation: 0,
      opacity: 1,
      visible: true,
      zIndex: 15,
      params: {},
    },
  ];
}
